//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CFontStyle.cpp
//  @ Date : 19.03.2014
//  @ Author : 
//
//


#include "CFontStyle.hpp"


bool CFontStyle::isBold() 
{
   return bold;
}

bool CFontStyle::isItalic() 
{
   return italic;
}

bool CFontStyle::isUnderline() 
{
   return underline;
}

bool CFontStyle::isStrikethrough() 
{
   return strikethrough;
}

bool CFontStyle::isSubscript() 
{
   return subscript;
}

bool CFontStyle::isSuperscript() 
{
   return superscript;
}

void CFontStyle::setBold(bool state) 
{
   bold = state;
}

void CFontStyle::setItalic(bool state) 
{
   italic = state;
}

void CFontStyle::setUnderline(bool state) 
{
   underline = state;
}

void CFontStyle::setStrikethrough(bool state) 
{
   strikethrough = state;
}

void CFontStyle::setSubscript(bool state) 
{
   subscript = state;
}

void CFontStyle::setSuperscript(bool state) 
{
   superscript = state;
}

bool CFontStyle::operator!=(CFontStyle & obj)
{
   if (this->bold != obj.bold)
   {
      return true;
   }
   if (this->italic != obj.italic)
   {
      return true;
   }
   if (this->underline != obj.underline)
   {
      return true;
   }
   if (this->strikethrough != obj.strikethrough)
   {
      return true;
   }
   if (this->subscript != obj.subscript)
   {
      return true;
   }
   if (this->superscript != obj.superscript)
   {
      return true;
   }

   return false;
}
