//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CFontStyle.hpp
//  @ Date : 19.03.2014
//  @ Author : 
//
//


#if !defined(_CFONTSTYLE_H)
#define _CFONTSTYLE_H

#include "StdAfx.h"

class CFontStyle {
public:
   CFontStyle():
      bold(0),
      italic(0),
      underline(0),
      strikethrough(0),
      subscript(0),
      superscript(0) {};
   explicit CFontStyle(CFontStyle * const oFontStyle):
      bold(oFontStyle->isBold()),
      italic(oFontStyle->isItalic()),
      underline(oFontStyle->isUnderline()),
      strikethrough(oFontStyle->isStrikethrough()),
      subscript(oFontStyle->isSubscript()),
      superscript(oFontStyle->isSuperscript()) {};
	bool isBold();
	bool isItalic();
	bool isUnderline();
	bool isStrikethrough();
	bool isSubscript();
	bool isSuperscript();
	void setBold(bool state);
	void setItalic(bool state);
	void setUnderline(bool state);
	void setStrikethrough(bool state);
	void setSubscript(bool state);
	void setSuperscript(bool state);
   bool operator!=(CFontStyle & obj);
private:  
	unsigned bold           : 1;
	unsigned italic         : 1;
	unsigned underline      : 1;
	unsigned strikethrough  : 1;
	unsigned subscript      : 1;
	unsigned superscript    : 1;
};

#endif  //_CFONTSTYLE_H
